name: deploy

on:
  push:
    branches:
      - main
      - ci/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: build
        run: |
          yarn
          yarn build
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "build/**/*"
          target: ${{ secrets.TARGET }}
    
